# Generated by Django 2.2.7 on 2019-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('scheme_image', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Scheme')),
            ],
        ),
    ]
