# Generated by Django 2.2.7 on 2019-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_name',
        ),
        migrations.AddField(
            model_name='book',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='owner_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
